# Generated by Django 4.2.7 on 2025-09-09 08:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_distance', models.FloatField(default=0.0, help_text='Daily car distance in kilometers')),
                ('car_efficiency', models.FloatField(default=8.0, help_text='Car fuel efficiency in L/100km')),
                ('public_transport_distance', models.FloatField(default=0.0, help_text='Daily public transport distance in kilometers')),
                ('flights_short', models.IntegerField(default=0, help_text='Number of short-haul flights per year')),
                ('flights_long', models.IntegerField(default=0, help_text='Number of long-haul flights per year')),
                ('electricity_usage', models.FloatField(default=0.0, help_text='Monthly electricity usage in kWh')),
                ('heating_gas', models.FloatField(default=0.0, help_text='Monthly natural gas usage in cubic meters')),
                ('renewable_energy', models.BooleanField(default=False, help_text='Uses renewable energy sources')),
                ('meat_consumption', models.CharField(choices=[('high', 'High (daily)'), ('medium', 'Medium (few times/week)'), ('low', 'Low (rarely)'), ('none', 'Vegetarian/Vegan')], default='medium', max_length=20)),
                ('local_food', models.BooleanField(default=False, help_text='Primarily buys local/organic food')),
                ('waste_recycling', models.BooleanField(default=True, help_text='Regularly recycles waste')),
                ('transport_emissions', models.FloatField(default=0.0, help_text='Transport emissions in kg CO2/year')),
                ('energy_emissions', models.FloatField(default=0.0, help_text='Energy emissions in kg CO2/year')),
                ('lifestyle_emissions', models.FloatField(default=0.0, help_text='Lifestyle emissions in kg CO2/year')),
                ('total_emissions', models.FloatField(default=0.0, help_text='Total carbon footprint in kg CO2/year')),
                ('eco_score', models.IntegerField(default=0, help_text='Eco-friendliness score out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommendations', models.JSONField(default=list, help_text='Personalized recommendations for reducing carbon footprint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carbon_calculations', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='challenges__user_id_252aae_idx'), models.Index(fields=['challenge', 'created_at'], name='challenges__challen_3900e4_idx')],
                'unique_together': {('user', 'challenge', 'created_at')},
            },
        ),
    ]
