# Generated by Django 4.2.7 on 2025-09-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_carbonfootprint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carbonfootprint',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_calculations', to='challenges.challenge'),
        ),
    ]
