# Render deployment configuration for CodeQuest backend
services:
  - type: web
    name: enviro-edu-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn --config gunicorn.conf.py config.wsgi:application
    healthCheckPath: /health/
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-backend-domain.onrender.com,your-custom-domain.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: enviro-edu-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app,https://your-custom-domain.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://your-frontend-domain.vercel.app,https://your-custom-domain.com
      - key: CORS_ALLOW_CREDENTIALS
        value: true
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SECURE_PROXY_SSL_HEADER
        value: HTTP_X_FORWARDED_PROTO,https
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SECURE_BROWSER_XSS_FILTER
        value: true
      - key: SECURE_CONTENT_TYPE_NOSNIFF
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: true
      - key: SECURE_HSTS_PRELOAD
        value: true
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@codequest.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: enviro-edu-redis
          property: connectionString
    
    # Auto-deploy from GitHub
    autoDeploy: true
    
    # Custom domains (optional)
    domains:
      - api.your-domain.com
    
    # Disk storage
    disk:
      name: enviro-edu-storage
      mountPath: /app/mediafiles
      sizeGB: 10

databases:
  - name: enviro-edu-db
    databaseName: enviro_edu
    user: enviro_edu_user
    plan: starter
    region: oregon
    
    # Automatic backups
    ipAllowList: []
    
    # Database configuration
    postgresMajorVersion: 15

# Redis for caching and sessions
  - name: enviro-edu-redis
    type: redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru
    
    # Redis configuration
    ipAllowList: []

# Static file service (optional, can use Django's collectstatic)
# - type: static
#   name: codequest-static
#   staticPublishPath: ./staticfiles
#   buildCommand: python manage.py collectstatic --noinput
#   domains:
#     - static.codequest.com