# Generated by Django 4.2.7 on 2025-09-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_quizresult_gameresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
